source 'https://rubygems.org'
gem 'json'
gem 'psych'
gem 'rest-client', '>=2.0'
# gem 'httpclient', '>=2.4'
gem 'net-ssh'
# gem 'net-ssh-multi'
# gem 'net-scp'
gem 'cucumber', '>=2.0'
# gem 'rspec', '~>2.14.1'
# gem 'rspec-expectations', '~>2.14.0'
# gem 'aws-sdk-v1'
# gem 'aws-sdk', '~> 2'
# gem 'timers'
## Logging
gem 'term-ansicolor'
## Webauto
gem 'watir-webdriver', '>=0.6.11'
#gem 'headless'
## Docs
# gem 'yard-cucumber' # works only with old cucumber
## tools
gem 'asciidoctor'
## Debugging
gem 'byebug'
gem 'pry'
# gem 'mongo'
# gem 'bson_ext'
# gem 'parseconfig'
# gem 'rake'
# gem 'rails', '~>3.2.0'
# gem 'rhc'
# gem 'mongoid'
# gem 'text-table'
# gem 'terminal-table'
