--- # cucushift framework configuration options
global:
  git_repo_url: https://github.com/openshift/cucushift
  git_repo_default_branch: v3

  debug_in_after_hook: false
  debug_in_after_hook_always: false

