--- # cucushift framework configuration options
global:
  git_repo_url: https://github.com/openshift/cucushift
  git_repo_default_branch: v3

  debug_in_after_hook: false
  debug_in_after_hook_always: false
  debug_attacher_timeout: false

  rest_default_auth: :bearer_token

  # base docker registry prefixes for quickstarts;
  #   (one is for the upstream community supported *projects* and the other one
  #   is for the Red Hat enterprise supported *products*);
  #   product one can be overriden by PRODUCT_DOCKER_REPO
  #   here "openshift" means "docker.io/openshift" as docker.io is the default
  #   repo; see examples in features/quickstarts/quickstarts.feature
  project_docker_repo: ""
  product_docker_repo: registry.access.redhat.com/

  # use CUCUSHIFT_DEFAULT_ENVIRONMENT instead of setting here
  # default_environment: ose

  # use CUCUSHIFT_TEST_CASE_MANAGER instead of setting here
  # test_case_manager: tcms

environments:
  ose:
    # hosts: use OPENSHIFT_ENV_OSE_HOSTS=host:role1:...,host2:role1:...
    hosts_type: SSHAccessibleHost
    # this is the user for remote access to the OpenShift nodes
    user: root
    type: StaticEnvironment
    user_manager: StaticUserManager
    # set users in OPENSHIFT_ENV_OSE_USER_MANAGER_USERS=user:password,...
    # user_manager_users: joe:redhat,alice:redhat
    #cli: MasterOsPerUserCliExecutor
    cli: SharedLocalCliExecutor
    admin_cli: MasterKubeconfigLocalAdminCliExecutor
    api_port: 8443
  origin:
    # hosts: use OPENSHIFT_ENV_OSE_HOSTS=host:role1:...,host2:role1:...
    hosts_type: SSHAccessibleHost
    # this is the user for remote access to the OpenShift nodes
    user: fedora
    type: StaticEnvironment
    user_manager: StaticUserManager
    # set users in OPENSHIFT_ENV_OSE_USER_MANAGER_USERS=user:password,...
    # user_manager_users: joe:redhat,alice:redhat
    cli: SharedLocalCliExecutor
    # cli: SharedLocalCliExecutor
    admin_cli: MasterKubeconfigLocalAdminCliExecutor
    api_port: 8443
  stage:
    hosts: api.stage.openshift.com:etcd:master:node
    web_console_url: https://console.stage.openshift.com
    hosts_type: Host # we can't basically access that host so this should work
    type: StaticEnvironment
    user_manager: StaticUserManager
    #set OPENSHIFT_ENV_STAGE_USER_MANAGER_USERS=:user_token1,:user_token2,...
    #user_manage_users:
    cli: SharedLocalCliExecutor
    admin_cli: false

optional_classes:
  tcms_tc_manager:
    include_path: tcms/tcms_manager
    class: CucuShift::TCMSManager
    opts: {}
services:
  AWS:
    create_opts:
      # for all options see http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Resource.html#create_instances-instance_method
      # the actual key-pair name is under the private repo and will be over-written
      key_name: "secret_key_pair"
      #instance_type: "c4.large"
      instance_type: "m3.medium"
      #image_id: my_image_id
      #subnet_id: my_subnet_id
      #placement:
      #  availability_zone: "us-east-1d"
      min_count: 1
      max_count: 1
      #security_groups: ["String"]
      #security_group_ids: ["String"]
      #block_device_mappings:
      #- device_name: "/dev/sda1"
      #  ebs:
      #    volume_size: 30

    config_opts:
      region: "us-east-1"

    tag_ready: "qe-ready"
    ami_types:
      fedora: "devenv-fedora_*"
      centos7: "devenv-centos7_*"
      rhel7: "devenv-rhel7_*"
      rhel7next: "devenv-rhel7next_*"
      devenv_v2: "devenv_*"
      devenv_stable_v2: "devenv-stage_*"
      raw: "ami-01743f64"
    hosts_type: SSHAccessibleHost
    cloud_type: aws
    # host_opts:
      # ssh_private_key: relative/path
      # user: the_username
