--- # cucushift framework configuration options
global:
  git_repo_url: https://github.com/openshift/cucushift
  git_repo_default_branch: v3

  debug_in_after_hook: false
  debug_in_after_hook_always: false

  rest_default_auth: :bearer_token

  # use CUCUSHIFT_DEFAULT_ENVIRONMENT instead of setting here
  # default_environment: ose

environments:
  ose:
    # hosts: use OPENSHIFT_ENV_OSE_HOSTS=host:role1:...,host2:role1:...
    ssh_user: root
    hosts_type: SSHAccessibleHost
    user: root
    type: StaticEnvironment
    user_manager: StaticUserManager
    # set users in OPENSHIFT_ENV_OSE_USER_MANAGER_USERS=user:password,...
    # user_manager_users: joe:redhat,alice:redhat
    cli: MasterOsPerUserCliExecutor
    # cli: SharedLocalCliExecutor
    #admin_cli: MasterOsAdminCliExecutor
    api_port: 8443
  stage:
    hosts: api.stg.openshift.com:etcd:master:node
    hosts_type: Host # we can't basically access that host so this should work
    type: StaticEnvironment
    user_manager: StaticUserManager
    #set OPENSHIFT_ENV_STAGE_USER_MANAGER_USERS=:user_token1,:user_token2,...
    #user_manage_users:
    cli: SharedLocalCliExecutor
    admin_cli: false
