--- # cucushift framework configuration options
global:
  git_repo_url: https://github.com/openshift/cucushift
  git_repo_default_branch: v3

  debug_in_after_hook: false
  debug_in_after_hook_always: false
  debug_attacher_timeout: false

  rest_default_auth: :bearer_token

  # base docker registry prefixes for quickstarts;
  #   (one is for the upstream community supported *projects* and the other one
  #   is for the Red Hat enterprise supported *products*);
  #   product one can be overriden by PRODUCT_DOCKER_REPO_PREFIX
  #   here "openshift" means "docker.io/openshift" as docker.io is the default
  #   repo; see examples in features/quickstarts/quickstarts.feature
  project_docker_repo: ""
  product_docker_repo: registry.access.redhat.com/

  # use CUCUSHIFT_DEFAULT_ENVIRONMENT instead of setting here
  # default_environment: ose

  # use CUCUSHIFT_TEST_CASE_MANAGER instead of setting here
  # test_case_manager: tcms

environments:
  ose:
    # hosts: use OPENSHIFT_ENV_OSE_HOSTS=host:role1:...,host2:role1:...
    hosts_type: SSHAccessibleHost
    # this is the user for remote access to the OpenShift nodes
    user: root
    type: StaticEnvironment
    user_manager: StaticUserManager
    # set users in OPENSHIFT_ENV_OSE_USER_MANAGER_USERS=user:password,...
    # user_manager_users: joe:redhat,alice:redhat
    #cli: MasterOsPerUserCliExecutor
    cli: SharedLocalCliExecutor
    admin_cli: MasterKubeconfigLocalAdminCliExecutor
    api_port: 8443
  origin:
    # hosts: use OPENSHIFT_ENV_OSE_HOSTS=host:role1:...,host2:role1:...
    hosts_type: SSHAccessibleHost
    # this is the user for remote access to the OpenShift nodes
    user: fedora
    type: StaticEnvironment
    user_manager: StaticUserManager
    # set users in OPENSHIFT_ENV_OSE_USER_MANAGER_USERS=user:password,...
    # user_manager_users: joe:redhat,alice:redhat
    cli: SharedLocalCliExecutor
    # cli: SharedLocalCliExecutor
    admin_cli: MasterKubeconfigLocalAdminCliExecutor
    api_port: 8443
  stage:
    hosts: api.stg.openshift.com:etcd:master:node
    hosts_type: Host # we can't basically access that host so this should work
    type: StaticEnvironment
    user_manager: StaticUserManager
    #set OPENSHIFT_ENV_STAGE_USER_MANAGER_USERS=:user_token1,:user_token2,...
    #user_manage_users:
    cli: SharedLocalCliExecutor
    admin_cli: false

optional_classes:
  tcms_tc_manager:
    include_path: tcms/tcms_manager
    class: CucuShift::TCMSManager
    opts: {}
services:
  AWS:
    # the actual key-pair name is under the private repo and will be over-written
    key_pair: "secret_key_pair"
    instance_type: "m3.medium"
    min_count: 1
    max_count: 1
    #instance_type: "c4.large"
    zone: "us-east-1d"
    region: "us-east-1"
    qe_ready: "qe-ready"
    fedora: "devenv-fedora_*"
    centos7: "devenv-centos7_*"
    rhel7: "devenv-rhel7_*"
    rhel7next: "devenv-rhel7next_*"
    devenv_wildcard: "devenv-*"
    stable_ami: "devenv-stage-*"
